### ISSUE TITLE
Auth error after signing to boom.money

### ISSUE THREAD

**Issue by friedger** [Light-Labs/stacks-wallet-web#12]
After signing the JWT there is an error in connect. Maybe related to #10 
```
[Connect] Error during auth request Error
    at t.<anonymous> (vendor.9c48b40c.js:45:54253)
    at l (vendor.9c48b40c.js:38:12048)
    at Generator._invoke (vendor.9c48b40c.js:38:13374)
    at Generator.next (vendor.9c48b40c.js:38:12473)
    at r (vendor.9c48b40c.js:38:64934)
```

**Comment by MarvinJanssen** [comment]
`appPrivateKey` not exported by Hiro Wallet. Resetting the master key causes this issue. Hiro Wallet expects a different wallet than the Ryder uses. Exports one address and signs with another.
